# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-21 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volts', '0003_auto_20180201_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Voltage Graphs', max_length=128)),
                ('banner', models.CharField(default='Raspberry Pi Voltage Grapher', max_length=128)),
                ('control', models.CharField(default='Temperature Recipe', max_length=128)),
                ('color', models.CharField(default='#FCA205', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='recipe_step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.FloatField(default=75.0)),
                ('duration', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='graph',
            name='value_field',
            field=models.CharField(default='volts', max_length=128),
        ),
    ]
